
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a6
  description: remove
  annotations:
    backstage.io/kubernetes-id: a6
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: neenspa/a6
spec:
  type: api
  lifecycle: production
  owner: amargheritini
